export const FETCH_MEAL_PLAN = 'FETCH_MEAL_PLAN';
export const FETCH_MEAL_PLAN_ERROR = 'FETCH_MEAL_PLAN_ERROR';
export const RECEIVE_MEAL_PLAN = 'RECEIVE_MEAL_PLAN';
export const CREATE_MEAL_PLAN = 'CREATE_MEAL_PLAN';
export const SUBSTITUTE_RECIPE = 'SUBSTITUTE_RECIPE';
