export const FETCH_DAY_PLAN = 'FETCH_DAY_PLAN';
export const FETCH_DAY_PLAN_ERROR = 'FETCH_DAY_PLAN_ERROR';
export const RECEIVE_DAY_PLAN = 'RECEIVE_DAY_PLAN';
export const CREATE_MEAL_PLAN = 'CREATE_MEAL_PLAN';
export const SUBSTITUTE_RECIPE = 'SUBSTITUTE_RECIPE';
