export const FETCH_DAY_PLAN = 'FETCH_DAY_PLAN';
export const FETCH_DAY_PLAN_ERROR = 'FETCH_DAY_PLAN_ERROR';
export const RECEIVE_DAY_PLAN = 'RECEIVE_DAY_PLAN';
export const SUBSTITUTE_RECIPE = 'SUBSTITUTE_RECIPE';

export const FETCH_SUBSTITUTE_RECIPE = 'FETCH_SUBSTITUTE_RECIPE';
export const FETCH_SUBSTITUTE_RECIPE_ERROR = 'FETCH_SUBSTITUTE_RECIPE_ERROR';
export const RECEIVE_SUBSTITUTE_RECIPE = 'RECEIVE_SUBSTITUTE_RECIPE';

export const CHANGE_RECIPE_MODAL_OPEN = 'CHANGE_RECIPE_MODAL_OPEN';
export const CHANGE_RECIPE_MODAL_CLOSE = 'CHANGE_RECIPE_MODAL_CLOSE';
